#FONCTIONS NUMPY

In [8]:
import numpy as np

Création d’un array, les paramètres peuvent être autre que des nombres entiers


In [9]:
liste = np.arange(0,8,.2)
liste

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8])

In [19]:
signal = np.random.randn(1000)

# fonctions = [np.max, np.min, np.median, np.mean, np.std]
fonctions = {
    "maximum" : np.max, 
    "minimum" : np.min, 
    "médiane" : np.median, 
    "moyenne" : np.mean, 
    "écart-type" : np.std
    }

def launch_functions(arr):
    print("–––")
    for name, function in fonctions.items() :
        print(name, ":", function(arr))

launch_functions(liste)
launch_functions(signal)

–––
maximum : 7.800000000000001
minimum : 0.0
médiane : 3.9000000000000004
moyenne : 3.9
écrat-type : 2.3086792761230392
–––
maximum : 3.6593807063845367
minimum : -3.56812402559721
médiane : 0.03822521087949808
moyenne : 0.012487005748448602
écrat-type : 0.970717916554293


La fonction **linspace()** crée un array en espaçant les éléments de manière équivalente. \
Le paramètre *stop* (second param) ne fonctionne pas comme d’habitude et inclus la valeur

In [26]:
liste_espacee = np.linspace(1,8,25)

type(liste_espace)

numpy.ndarray

In [29]:
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
x = np.asarray([f for f in range(10)])
indice = x>5
print(indice)
x[indice] = 10 
print(x)
x[indice] = 20 
print(x)


[False False False False False False  True  True  True  True]
[ 0  1  2  3  4  5 10 10 10 10]
[ 0  1  2  3  4  5 20 20 20 20]


solutions pour remplacer les elements d’une liste par 0 ou 1 en fonction d’une condition : 

In [63]:
li = np.array([f for f in range(11)])

li = li > 5
li = li + 4
li = li * 5

li

array([20, 20, 20, 20, 20, 20, 25, 25, 25, 25, 25])

In [ ]:
li = [0,1,0,1,0,1]

res = []
for i, x in enumerate(li) :
    if x : res.append(i)

res